version: 2

sphinx:
    configuration: docs/source/conf.py

formats:
    - pdf

conda:
    environment: sphinx.yml

python:
    install:
        - method: pip
          path: .

build:
    image: latest
